version: 1.4.{build}
branches:
  only:
  - master
skip_commits:
  message: /updated readme.*/
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore
build:
  project: Topshelf.Owin.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  server: 
  api_key:
    secure: gDsE3gJOuBDFt9vp16x9q1KLSFQ8OMHBRmwwvhE19uO+7gbpK5lCiFp0OUB6Ivou
